name: Build plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build plugin jar
        run: ./gradlew clean shadowJar

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: plugin/build/libs/*.jar
